theme: jekyll-theme-architect
show_downloads: false
title: "[翻訳記事]マイクロフロントエンド"
description: "マイクロサービスのフロントエンドへの応用"
google_analytics: UA-123245291-1
github:
  is_project_page: true
  repository_url: https://github.com/koiketakayuki/micro-frontends
